name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    env:
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JWT_SECRET_KEY: ${{ secrets.API_KEY }}
      EMAIL_DEFAULT: ${{ secrets.EMAIL_DEFAULT }}
    
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.3'

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        run: |
          cp .github/config/database.yml config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: Run RSpec
        run: COVERAGE=true bundle exec rspec  --require rails_helper

      - name: Run rubocop
        run: |
          bundle exec rubocop
